In [1]:
# import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt
import os
from skimage.io import imread_collection
from skimage import data, img_as_float, io, exposure
import matplotlib
from natsort import natsorted, ns
# from fastai.vision.all import *

In [2]:
# listFiles = os.listdir('train_v2')
# listFiles = natsorted(listFiles)
# allImages = []
# for filename in listFiles:
#     temp = os.path.join('train_v2',filename)
#     allImages.append(io.imread(temp))

In [3]:
from sklearn.model_selection import train_test_split
import pandas as pd
train_names = [f for f in os.listdir("train_v2")]
tr_n, val_n = train_test_split(train_names, test_size=0.05, random_state=42)
segmentation_df = pd.read_csv(os.path.join('./', './train_ship_segmentations_v2.csv'))

In [4]:
segmentation_df

ImageId                                      EncodedPixels
0       00003e153.jpg                                                NaN
1       0001124c7.jpg                                                NaN
2       000155de5.jpg  264661 17 265429 33 266197 33 266965 33 267733...
3       000194a2d.jpg  360486 1 361252 4 362019 5 362785 8 363552 10 ...
4       000194a2d.jpg  51834 9 52602 9 53370 9 54138 9 54906 9 55674 ...
...               ...                                                ...
231718  fffedbb6b.jpg                                                NaN
231719  ffff2aa57.jpg                                                NaN
231720  ffff6e525.jpg                                                NaN
231721  ffffc50b4.jpg                                                NaN
231722  ffffe97f3.jpg                                                NaN

[231723 rows x 2 columns]

In [5]:
trainAllImages = []
for i in range(len(segmentation_df)):
    temp = segmentation_df.loc[i]["EncodedPixels"]
    if(type(temp)==str):
        trainAllImages.append(segmentation_df.loc[i]["ImageId"])
print(trainAllImages[0])

000155de5.jpg


In [6]:
print(trainAllImages[1])

000194a2d.jpg


In [7]:
trainImages = natsorted(trainAllImages)
imagesList = []
count = 0
for i in trainImages:
    count+=1
    temp1 = os.path.join('train_v2',i)
#     allImages.append(io.imread(temp))
    imagesList.append(io.imread(temp1))
    if(count>1000):
        break

In [8]:
len(imagesList)

1001

In [9]:
print(imagesList[1])

[[[22 73 74]
  [18 69 70]
  [13 64 65]
  ...
  [21 72 73]
  [21 72 73]
  [21 72 73]]

 [[17 68 69]
  [15 66 67]
  [12 63 64]
  ...
  [22 73 74]
  [21 72 73]
  [21 72 73]]

 [[14 65 66]
  [13 64 65]
  [13 64 65]
  ...
  [21 72 73]
  [20 71 72]
  [19 70 71]]

 ...

 [[15 70 73]
  [15 70 73]
  [15 70 73]
  ...
  [18 81 90]
  [18 81 90]
  [17 80 89]]

 [[16 71 74]
  [17 72 75]
  [17 72 75]
  ...
  [15 78 87]
  [18 81 90]
  [19 82 91]]

 [[18 73 76]
  [18 73 76]
  [18 73 76]
  ...
  [13 76 85]
  [16 79 88]
  [19 82 91]]]


In [10]:
from skimage import filters
smoothenedImages = []
# smooothingResult = filters.gaussian(imagesList[1], sigma=1)
# io.imshow(smooothingResult)
for i in imagesList:
    smoothingResult = filters.gaussian(i,sigma = 0.5)
    smoothenedImages.append(smoothingResult)

C:\Users\Atul\AppData\Local\Temp/ipykernel_16824/2774407464.py:6: RuntimeWarning: Images with dimensions (M, N, 3) are interpreted as 2D+RGB by default. Use `multichannel=False` to interpret as 3D image with last dimension of length 3.
  smoothingResult = filters.gaussian(i,sigma = 0.5)


MemoryError: Unable to allocate 13.5 MiB for an array with shape (768, 768, 3) and data type float64

In [ ]:
io.imshow(imagesList[1])

In [ ]:
imagesEdges = []
for i in smoothenedImages:
    edgesResult = filters.sobel(i,sigma = 0.5)
    imagesEdges.append(edgesResult)